"""
Confluence tools for documentation publishing.

These tools are executed locally when the agent returns control.
"""

import hashlib
from datetime import UTC, datetime
from typing import Any, Optional

from atlassian import Confluence
from atlassian.errors import ApiError

from code2doc.config.settings import get_settings
from code2doc.tools.base import BaseTool, ToolResult
from code2doc.utils.logging import get_logger

logger = get_logger("confluence_tools")


class ConfluenceClient:
    """
    Wrapper around atlassian-python-api Confluence client.

    Provides a simplified interface with version management support.
    """

    _instance: Optional["ConfluenceClient"] = None

    def __init__(self, url: str, username: str, access_token: str, space_key: str):
        """
        Initialize Confluence client.

        Args:
            url: Confluence instance URL
            username: Username or email
            access_token: API token
            space_key: Default space key
        """
        self.url = url.rstrip("/")
        self.space_key = space_key
        self._client = Confluence(
            url=self.url,
            username=username,
            password=access_token,
            cloud=True,  # Assume Confluence Cloud
        )

    @classmethod
    def get_instance(cls) -> "ConfluenceClient":
        """Get or create a singleton Confluence client instance."""
        if cls._instance is None:
            settings = get_settings()
            if not settings.confluence.api_token:
                raise ValueError("Confluence API token not configured")
            if not settings.confluence.url:
                raise ValueError("Confluence URL not configured")
            cls._instance = cls(
                url=settings.confluence.url,
                username=settings.confluence.username or "",
                access_token=settings.confluence.api_token,
                space_key=settings.confluence.space_key,
            )
        return cls._instance

    @classmethod
    def reset_instance(cls) -> None:
        """Reset the singleton instance (useful for testing)."""
        cls._instance = None

    @staticmethod
    def compute_content_hash(content: str) -> str:
        """
        Compute MD5 hash of content for change detection.

        Args:
            content: Content to hash

        Returns:
            MD5 hash string
        """
        return hashlib.md5(content.encode("utf-8")).hexdigest()

    @staticmethod
    def generate_version_comment(
        agent_name: str | None = None,
        commit_ref: str | None = None,
        include_timestamp: bool = True,
    ) -> str:
        """
        Generate a version comment for Confluence page updates.

        Args:
            agent_name: Name of the agent that generated the content
            commit_ref: Git commit reference
            include_timestamp: Whether to include timestamp

        Returns:
            Version comment string
        """
        parts = ["Auto-generated by Code-2-Doc"]

        if include_timestamp:
            timestamp = datetime.now(UTC).isoformat()
            parts.append(f"on {timestamp}")

        if commit_ref:
            parts.append(f"@ commit {commit_ref[:8]}")

        if agent_name:
            parts.append(f"| Agent: {agent_name}")

        return " ".join(parts)

    def get_page_by_title(
        self,
        title: str,
        space_key: str | None = None,
    ) -> dict[str, Any] | None:
        """
        Get a page by its title.

        Args:
            title: Page title
            space_key: Space key (uses default if not provided)

        Returns:
            Page data or None if not found
        """
        space = space_key or self.space_key
        try:
            page: dict[str, Any] | None = self._client.get_page_by_title(
                space=space,
                title=title,
                expand="body.storage,version",
            )
            return page
        except Exception:
            return None

    def get_page(self, page_id: str) -> dict[str, Any] | None:
        """
        Get a page by ID.

        Args:
            page_id: Confluence page ID

        Returns:
            Page data or None if not found
        """
        try:
            page: dict[str, Any] = self._client.get_page_by_id(
                page_id=page_id,
                expand="body.storage,version",
            )
            return page
        except Exception:
            return None

    def create_page(
        self,
        title: str,
        content: str,
        space_key: str | None = None,
        parent_id: str | None = None,
    ) -> dict[str, Any]:
        """
        Create a new Confluence page.

        Args:
            title: Page title
            content: Page content (markdown will be converted)
            space_key: Space key (uses default if not provided)
            parent_id: Parent page ID (optional)

        Returns:
            Created page data
        """
        space = space_key or self.space_key

        # Convert markdown to Confluence storage format
        # Note: atlassian-python-api handles basic conversion
        result: dict[str, Any] = self._client.create_page(
            space=space,
            title=title,
            body=content,
            parent_id=parent_id,
            representation="wiki",  # Use wiki markup
        )

        logger.info(f"Created page: {title} (ID: {result['id']})")
        return result

    def update_page(
        self,
        page_id: str,
        title: str,
        content: str,
        version_comment: str | None = None,
    ) -> dict[str, Any]:
        """
        Update an existing Confluence page.

        Args:
            page_id: Page ID to update
            title: New page title
            content: New page content
            version_comment: Comment for version history

        Returns:
            Updated page data
        """
        # Get current version
        current_page = self.get_page(page_id)
        if not current_page:
            raise ValueError(f"Page not found: {page_id}")

        current_version = current_page["version"]["number"]

        result: dict[str, Any] = self._client.update_page(
            page_id=page_id,
            title=title,
            body=content,
            representation="wiki",
            minor_edit=False,
            version_comment=version_comment,
        )

        logger.info(
            f"Updated page: {title} (ID: {page_id}, "
            f"version: {current_version} -> {result['version']['number']})"
        )
        return result

    def find_or_create_page(
        self,
        title: str,
        content: str,
        space_key: str | None = None,
        parent_id: str | None = None,
        version_comment: str | None = None,
        skip_unchanged: bool = True,
    ) -> tuple[dict[str, Any], bool]:
        """
        Find an existing page by title or create a new one.

        If the page exists and content has changed, updates it with a new version.

        Args:
            title: Page title
            content: Page content
            space_key: Space key
            parent_id: Parent page ID for new pages
            version_comment: Comment for version history
            skip_unchanged: Skip update if content hash matches

        Returns:
            Tuple of (page data, was_created)
        """
        space = space_key or self.space_key

        # Check if page exists
        existing_page = self.get_page_by_title(title, space)

        if existing_page is None:
            # Create new page
            page = self.create_page(
                title=title,
                content=content,
                space_key=space,
                parent_id=parent_id,
            )
            return page, True

        # Page exists - check if content changed
        if skip_unchanged:
            existing_content = existing_page.get("body", {}).get("storage", {}).get("value", "")
            existing_hash = self.compute_content_hash(existing_content)
            new_hash = self.compute_content_hash(content)

            if existing_hash == new_hash:
                logger.info(f"Page unchanged, skipping update: {title}")
                return existing_page, False

        # Update existing page
        page = self.update_page(
            page_id=existing_page["id"],
            title=title,
            content=content,
            version_comment=version_comment,
        )
        return page, False

    def search_pages(
        self,
        query: str,
        space_key: str | None = None,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Search for pages in Confluence.

        Args:
            query: Search query
            space_key: Space key to search in
            limit: Maximum results

        Returns:
            List of matching pages
        """
        space = space_key or self.space_key

        cql = f'space = "{space}" AND text ~ "{query}"'
        results: dict[str, Any] = self._client.cql(cql, limit=limit)

        return list(results.get("results", []))


class CreatePageTool(BaseTool):
    """Tool to create a new Confluence page."""

    @property
    def name(self) -> str:
        return "create_page"

    @property
    def description(self) -> str:
        return "Create a new Confluence page"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Page title following naming convention",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "Page content in wiki markup or markdown format",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key (uses default if not provided)",
                "type": "string",
                "required": False,
            },
            "parent_id": {
                "description": "Parent page ID for hierarchy",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.create_page(
                title=kwargs["title"],
                content=kwargs["content"],
                space_key=kwargs.get("space_key"),
                parent_id=kwargs.get("parent_id"),
            )
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "url": f"{client.url}/wiki/spaces/{client.space_key}/pages/{page['id']}",
                },
                action="created",
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to create page: {str(e)}")


class UpdatePageTool(BaseTool):
    """Tool to update an existing Confluence page."""

    @property
    def name(self) -> str:
        return "update_page"

    @property
    def description(self) -> str:
        return "Update an existing Confluence page, creating a new version"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "page_id": {
                "description": "Confluence page ID",
                "type": "string",
                "required": True,
            },
            "title": {
                "description": "Page title",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "New page content",
                "type": "string",
                "required": True,
            },
            "version_comment": {
                "description": "Comment for version history",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()

            version_comment = kwargs.get("version_comment")
            if not version_comment:
                version_comment = client.generate_version_comment()

            page = client.update_page(
                page_id=kwargs["page_id"],
                title=kwargs["title"],
                content=kwargs["content"],
                version_comment=version_comment,
            )
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                },
                action="updated",
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to update page: {str(e)}")


class FindOrCreatePageTool(BaseTool):
    """Tool to find or create a Confluence page with version management."""

    @property
    def name(self) -> str:
        return "find_or_create_page"

    @property
    def description(self) -> str:
        return (
            "Find existing page by title or create new one. "
            "If exists, updates with new version (skips if unchanged)."
        )

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Page title following naming convention",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "Page content in wiki markup or markdown format",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
            "parent_id": {
                "description": "Parent page ID for new pages",
                "type": "string",
                "required": False,
            },
            "version_comment": {
                "description": "Comment for version history",
                "type": "string",
                "required": False,
            },
            "agent_name": {
                "description": "Name of the agent generating the content",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()

            version_comment = kwargs.get("version_comment")
            if not version_comment:
                version_comment = client.generate_version_comment(
                    agent_name=kwargs.get("agent_name"),
                )

            page, was_created = client.find_or_create_page(
                title=kwargs["title"],
                content=kwargs["content"],
                space_key=kwargs.get("space_key"),
                parent_id=kwargs.get("parent_id"),
                version_comment=version_comment,
            )

            action = "created" if was_created else "updated"
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "url": f"{client.url}/wiki/spaces/{client.space_key}/pages/{page['id']}",
                    "version": page.get("version", {}).get("number", 1),
                },
                action=action,
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to find or create page: {str(e)}")


class SearchPagesTool(BaseTool):
    """Tool to search for pages in Confluence."""

    @property
    def name(self) -> str:
        return "search_pages"

    @property
    def description(self) -> str:
        return "Search for existing pages in Confluence"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "query": {
                "description": "Search query",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
            "limit": {
                "description": "Maximum number of results (default: 10)",
                "type": "integer",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            results = client.search_pages(
                query=kwargs["query"],
                space_key=kwargs.get("space_key"),
                limit=kwargs.get("limit", 10),
            )

            pages = [
                {
                    "id": r.get("content", {}).get("id"),
                    "title": r.get("content", {}).get("title"),
                    "type": r.get("content", {}).get("type"),
                }
                for r in results
            ]

            return ToolResult.success(pages, count=len(pages))
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to search pages: {str(e)}")


class GetPageTool(BaseTool):
    """Tool to get a Confluence page by ID."""

    @property
    def name(self) -> str:
        return "get_page"

    @property
    def description(self) -> str:
        return "Get content of an existing Confluence page by ID"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "page_id": {
                "description": "Confluence page ID",
                "type": "string",
                "required": True,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.get_page(kwargs["page_id"])

            if page is None:
                return ToolResult.failure(f"Page not found: {kwargs['page_id']}")

            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                    "content": page.get("body", {}).get("storage", {}).get("value", ""),
                }
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to get page: {str(e)}")


class GetPageByTitleTool(BaseTool):
    """Tool to get a Confluence page by title."""

    @property
    def name(self) -> str:
        return "get_page_by_title"

    @property
    def description(self) -> str:
        return "Get a Confluence page by its title in a specific space"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Exact page title",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.get_page_by_title(
                title=kwargs["title"],
                space_key=kwargs.get("space_key"),
            )

            if page is None:
                return ToolResult.failure(f"Page not found: {kwargs['title']}")

            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                    "content": page.get("body", {}).get("storage", {}).get("value", ""),
                }
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to get page by title: {str(e)}")
