"""
Confluence tools for LangGraph agents.

These tools use the @tool decorator for LangGraph/LangChain compatibility.
They wrap the existing ConfluenceClient functionality.
"""

import json

from langchain_core.tools import tool

from code2doc.tools.confluence_tools import ConfluenceClient
from code2doc.utils.logging import get_logger

logger = get_logger("tools.confluence")


@tool
def find_or_create_page(
    space_key: str,
    title: str,
    content: str,
    parent_id: str | None = None,
    version_comment: str = "Auto-generated by Code-2-Doc",
) -> str:
    """Find an existing Confluence page by title or create a new one.

    If the page exists and content has changed, it will be updated with a new version.
    If content is unchanged, the update is skipped.

    Use this tool to publish documentation to Confluence.

    Args:
        space_key: Confluence space key (e.g., 'DOCS', 'TEAM')
        title: Page title - should follow naming convention [Project] - [Doc Type]
        content: Page content in wiki markup or markdown format
        parent_id: Optional parent page ID for document hierarchy
        version_comment: Comment for version history

    Returns:
        JSON with page_id, title, url, and action taken (created/updated/unchanged)
    """
    try:
        client = ConfluenceClient.get_instance()

        page, was_created = client.find_or_create_page(
            title=title,
            content=content,
            space_key=space_key,
            parent_id=parent_id,
            version_comment=version_comment,
        )

        action = "created" if was_created else "updated"
        result = {
            "page_id": page["id"],
            "title": page["title"],
            "url": f"{client.url}/wiki/spaces/{space_key}/pages/{page['id']}",
            "version": page.get("version", {}).get("number", 1),
            "action": action,
        }
        return json.dumps(result, indent=2)

    except Exception as e:
        logger.error(f"Failed to find or create page: {e}")
        return json.dumps({"error": str(e)})


@tool
def get_page_by_title(
    space_key: str,
    title: str,
) -> str:
    """Get a Confluence page by its title.

    Use this tool to check if a page already exists or to read existing documentation.

    Args:
        space_key: Confluence space key
        title: Exact page title to search for

    Returns:
        JSON with page content and metadata, or not_found status if page doesn't exist
    """
    try:
        client = ConfluenceClient.get_instance()
        page = client.get_page_by_title(title=title, space_key=space_key)

        if page is None:
            logger.warning(f"Page not found: {title} - it will be created if using find_or_create_page")
            return json.dumps({"status": "not_found", "title": title, "message": f"Page '{title}' does not exist yet"})

        result = {
            "status": "found",
            "page_id": page["id"],
            "title": page["title"],
            "version": page["version"]["number"],
            "content": page.get("body", {}).get("storage", {}).get("value", ""),
        }
        return json.dumps(result, indent=2)

    except Exception as e:
        logger.error(f"Failed to get page by title: {e}")
        return json.dumps({"error": str(e)})


@tool
def search_pages(
    space_key: str,
    query: str,
    limit: int = 10,
) -> str:
    """Search for pages in Confluence.

    Use this tool to find related documentation or check for existing pages.

    Args:
        space_key: Confluence space key to search in
        query: Search query text
        limit: Maximum number of results (default: 10)

    Returns:
        JSON list of matching pages with id, title, and type
    """
    try:
        client = ConfluenceClient.get_instance()
        results = client.search_pages(
            query=query,
            space_key=space_key,
            limit=limit,
        )

        pages = [
            {
                "id": r.get("content", {}).get("id"),
                "title": r.get("content", {}).get("title"),
                "type": r.get("content", {}).get("type"),
            }
            for r in results
        ]

        return json.dumps(pages, indent=2)

    except Exception as e:
        logger.error(f"Failed to search pages: {e}")
        return json.dumps({"error": str(e)})


@tool
def create_page(
    space_key: str,
    title: str,
    content: str,
    parent_id: str | None = None,
) -> str:
    """Create a new Confluence page.

    Use this tool when you need to create a new page and are sure it doesn't exist.
    For most cases, prefer find_or_create_page which handles existing pages.

    Args:
        space_key: Confluence space key
        title: Page title
        content: Page content in wiki markup or markdown format
        parent_id: Optional parent page ID

    Returns:
        JSON with created page details
    """
    try:
        client = ConfluenceClient.get_instance()
        page = client.create_page(
            title=title,
            content=content,
            space_key=space_key,
            parent_id=parent_id,
        )

        result = {
            "page_id": page["id"],
            "title": page["title"],
            "url": f"{client.url}/wiki/spaces/{space_key}/pages/{page['id']}",
        }
        return json.dumps(result, indent=2)

    except Exception as e:
        logger.error(f"Failed to create page: {e}")
        return json.dumps({"error": str(e)})


@tool
def update_page(
    page_id: str,
    title: str,
    content: str,
    version_comment: str | None = None,
) -> str:
    """Update an existing Confluence page.

    Creates a new version of the page with the updated content.

    Args:
        page_id: Confluence page ID to update
        title: Page title (can be changed)
        content: New page content
        version_comment: Optional comment for version history

    Returns:
        JSON with updated page details
    """
    try:
        client = ConfluenceClient.get_instance()

        if not version_comment:
            version_comment = client.generate_version_comment()

        page = client.update_page(
            page_id=page_id,
            title=title,
            content=content,
            version_comment=version_comment,
        )

        result = {
            "page_id": page["id"],
            "title": page["title"],
            "version": page["version"]["number"],
        }
        return json.dumps(result, indent=2)

    except Exception as e:
        logger.error(f"Failed to update page: {e}")
        return json.dumps({"error": str(e)})


# Collect all Confluence tools for easy import
confluence_tools = [
    find_or_create_page,
    get_page_by_title,
    search_pages,
    create_page,
    update_page,
]
