"""
Confluence tools for documentation publishing.

These tools are executed locally when the agent returns control.
"""

import hashlib
import re
from datetime import UTC, datetime
from typing import Any, Optional

from atlassian import Confluence
from atlassian.errors import ApiError

from code2doc.config.settings import get_settings
from code2doc.tools.base import BaseTool, ToolResult
from code2doc.utils.logging import get_logger

logger = get_logger("confluence_tools")


def markdown_to_confluence_storage(markdown_content: str) -> str:
    """
    Convert Markdown content to Confluence storage format (XHTML).

    This converter handles the most common Markdown elements used in
    documentation generated by the code2doc agents.

    Args:
        markdown_content: Markdown formatted text

    Returns:
        Confluence storage format (XHTML)
    """
    content = markdown_content

    # Normalize line endings
    content = content.replace("\r\n", "\n")

    # Process code blocks first (before other transformations)
    # Match fenced code blocks with optional language
    def replace_code_block(match: re.Match[str]) -> str:
        language = match.group(1) or "text"
        code = match.group(2)
        # Escape HTML entities in code
        code = code.replace("&", "&amp;")
        code = code.replace("<", "&lt;")
        code = code.replace(">", "&gt;")
        return f'<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">{language}</ac:parameter><ac:plain-text-body><![CDATA[{code}]]></ac:plain-text-body></ac:structured-macro>'

    content = re.sub(
        r"```(\w*)\n(.*?)```",
        replace_code_block,
        content,
        flags=re.DOTALL,
    )

    # Process inline code (before other inline formatting)
    content = re.sub(r"`([^`]+)`", r"<code>\1</code>", content)

    # Process tables
    def replace_table(match: re.Match[str]) -> str:
        table_text = match.group(0)
        lines = table_text.strip().split("\n")

        # Filter out separator lines (|---|---|)
        data_lines = [line for line in lines if not re.match(r"^\s*\|[\s\-:|]+\|\s*$", line)]

        if not data_lines:
            return table_text

        html = '<table class="wrapped"><colgroup><col /><col /></colgroup><tbody>'

        for i, line in enumerate(data_lines):
            # Split by | and filter empty cells
            cells = [cell.strip() for cell in line.split("|")]
            cells = [cell for cell in cells if cell]  # Remove empty strings

            if not cells:
                continue

            html += "<tr>"
            tag = "th" if i == 0 else "td"
            for cell in cells:
                # Process inline formatting within cells
                cell = process_inline_formatting(cell)
                html += f"<{tag}>{cell}</{tag}>"
            html += "</tr>"

        html += "</tbody></table>"
        return html

    # Match tables (lines starting with |)
    content = re.sub(
        r"(?:^\|.+\|\s*\n)+",
        replace_table,
        content,
        flags=re.MULTILINE,
    )

    # Process headings (must be done before paragraph processing)
    content = re.sub(r"^######\s+(.+)$", r"<h6>\1</h6>", content, flags=re.MULTILINE)
    content = re.sub(r"^#####\s+(.+)$", r"<h5>\1</h5>", content, flags=re.MULTILINE)
    content = re.sub(r"^####\s+(.+)$", r"<h4>\1</h4>", content, flags=re.MULTILINE)
    content = re.sub(r"^###\s+(.+)$", r"<h3>\1</h3>", content, flags=re.MULTILINE)
    content = re.sub(r"^##\s+(.+)$", r"<h2>\1</h2>", content, flags=re.MULTILINE)
    content = re.sub(r"^#\s+(.+)$", r"<h1>\1</h1>", content, flags=re.MULTILINE)

    # Process horizontal rules
    content = re.sub(r"^---+\s*$", "<hr />", content, flags=re.MULTILINE)
    content = re.sub(r"^___+\s*$", "<hr />", content, flags=re.MULTILINE)
    content = re.sub(r"^\*\*\*+\s*$", "<hr />", content, flags=re.MULTILINE)

    # Process unordered lists
    def replace_unordered_list(match: re.Match[str]) -> str:
        list_text = match.group(0)
        items = re.findall(r"^[\*\-]\s+(.+)$", list_text, re.MULTILINE)
        if not items:
            return list_text
        html = "<ul>"
        for item in items:
            item = process_inline_formatting(item)
            html += f"<li>{item}</li>"
        html += "</ul>"
        return html

    content = re.sub(
        r"(?:^[\*\-]\s+.+\n?)+",
        replace_unordered_list,
        content,
        flags=re.MULTILINE,
    )

    # Process ordered lists
    def replace_ordered_list(match: re.Match[str]) -> str:
        list_text = match.group(0)
        items = re.findall(r"^\d+\.\s+(.+)$", list_text, re.MULTILINE)
        if not items:
            return list_text
        html = "<ol>"
        for item in items:
            item = process_inline_formatting(item)
            html += f"<li>{item}</li>"
        html += "</ol>"
        return html

    content = re.sub(
        r"(?:^\d+\.\s+.+\n?)+",
        replace_ordered_list,
        content,
        flags=re.MULTILINE,
    )

    # Process inline formatting for remaining content
    content = process_inline_formatting(content)

    # Process links
    content = re.sub(
        r"\[([^\]]+)\]\(([^)]+)\)",
        r'<a href="\2">\1</a>',
        content,
    )

    # Process paragraphs (text blocks separated by blank lines)
    # Split by double newlines, wrap non-HTML blocks in <p> tags
    paragraphs = re.split(r"\n\n+", content)
    processed_paragraphs = []

    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
        # Don't wrap if already an HTML block element
        if re.match(
            r"^<(h[1-6]|ul|ol|table|hr|ac:structured-macro|p|div|blockquote)",
            para,
            re.IGNORECASE,
        ):
            processed_paragraphs.append(para)
        else:
            # Replace single newlines with <br /> for line breaks within paragraphs
            para = para.replace("\n", "<br />")
            processed_paragraphs.append(f"<p>{para}</p>")

    content = "\n".join(processed_paragraphs)

    return content


def process_inline_formatting(text: str) -> str:
    """
    Process inline Markdown formatting (bold, italic, strikethrough).

    Args:
        text: Text with inline Markdown formatting

    Returns:
        Text with HTML formatting
    """
    # Bold and italic combined (***text*** or ___text___)
    text = re.sub(r"\*\*\*([^*]+)\*\*\*", r"<strong><em>\1</em></strong>", text)
    text = re.sub(r"___([^_]+)___", r"<strong><em>\1</em></strong>", text)

    # Bold (**text** or __text__)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__([^_]+)__", r"<strong>\1</strong>", text)

    # Italic (*text* or _text_) - be careful not to match inside words
    text = re.sub(r"(?<![*\w])\*([^*]+)\*(?![*\w])", r"<em>\1</em>", text)
    text = re.sub(r"(?<![_\w])_([^_]+)_(?![_\w])", r"<em>\1</em>", text)

    # Strikethrough (~~text~~)
    text = re.sub(r"~~([^~]+)~~", r"<del>\1</del>", text)

    return text


class ConfluenceClient:
    """
    Wrapper around atlassian-python-api Confluence client.

    Provides a simplified interface with version management support.
    """

    _instance: Optional["ConfluenceClient"] = None

    def __init__(self, url: str, username: str, access_token: str, space_key: str):
        """
        Initialize Confluence client.

        Args:
            url: Confluence instance URL
            username: Username or email
            access_token: API token
            space_key: Default space key
        """
        self.url = url.rstrip("/")
        self.space_key = space_key
        self._client = Confluence(
            url=self.url,
            username=username,
            password=access_token,
            cloud=True,  # Assume Confluence Cloud
        )

    @classmethod
    def get_instance(cls) -> "ConfluenceClient":
        """Get or create a singleton Confluence client instance."""
        if cls._instance is None:
            settings = get_settings()
            if not settings.confluence.api_token:
                raise ValueError("Confluence API token not configured")
            if not settings.confluence.url:
                raise ValueError("Confluence URL not configured")
            cls._instance = cls(
                url=settings.confluence.url,
                username=settings.confluence.username or "",
                access_token=settings.confluence.api_token,
                space_key=settings.confluence.space_key,
            )
        return cls._instance

    @classmethod
    def reset_instance(cls) -> None:
        """Reset the singleton instance (useful for testing)."""
        cls._instance = None

    @staticmethod
    def compute_content_hash(content: str) -> str:
        """
        Compute MD5 hash of content for change detection.

        Args:
            content: Content to hash

        Returns:
            MD5 hash string
        """
        return hashlib.md5(content.encode("utf-8")).hexdigest()

    @staticmethod
    def generate_version_comment(
        agent_name: str | None = None,
        commit_ref: str | None = None,
        include_timestamp: bool = True,
    ) -> str:
        """
        Generate a version comment for Confluence page updates.

        Args:
            agent_name: Name of the agent that generated the content
            commit_ref: Git commit reference
            include_timestamp: Whether to include timestamp

        Returns:
            Version comment string
        """
        parts = ["Auto-generated by Code-2-Doc"]

        if include_timestamp:
            timestamp = datetime.now(UTC).isoformat()
            parts.append(f"on {timestamp}")

        if commit_ref:
            parts.append(f"@ commit {commit_ref[:8]}")

        if agent_name:
            parts.append(f"| Agent: {agent_name}")

        return " ".join(parts)

    def get_page_by_title(
        self,
        title: str,
        space_key: str | None = None,
    ) -> dict[str, Any] | None:
        """
        Get a page by its title.

        Args:
            title: Page title
            space_key: Space key (uses default if not provided)

        Returns:
            Page data or None if not found
        """
        space = space_key or self.space_key
        try:
            page: dict[str, Any] | None = self._client.get_page_by_title(
                space=space,
                title=title,
                expand="body.storage,version",
            )
            return page
        except Exception:
            return None

    def get_page(self, page_id: str) -> dict[str, Any] | None:
        """
        Get a page by ID.

        Args:
            page_id: Confluence page ID

        Returns:
            Page data or None if not found
        """
        try:
            page: dict[str, Any] = self._client.get_page_by_id(
                page_id=page_id,
                expand="body.storage,version",
            )
            return page
        except Exception:
            return None

    def create_page(
        self,
        title: str,
        content: str,
        space_key: str | None = None,
        parent_id: str | None = None,
        content_format: str = "markdown",
    ) -> dict[str, Any]:
        """
        Create a new Confluence page.

        Args:
            title: Page title
            content: Page content (markdown by default, will be converted to storage format)
            space_key: Space key (uses default if not provided)
            parent_id: Parent page ID (uses CONFLUENCE_PARENT_PAGE_ID from settings if not provided)
            content_format: Content format - 'markdown' (default), 'storage', or 'wiki'

        Returns:
            Created page data
        """
        space = space_key or self.space_key

        # Use default parent_id from settings if not provided
        if parent_id is None:
            settings = get_settings()
            parent_id = settings.confluence.parent_page_id

        # Convert content based on format
        if content_format == "markdown":
            # Convert markdown to Confluence storage format (XHTML)
            storage_content = markdown_to_confluence_storage(content)
            representation = "storage"
        elif content_format == "storage":
            storage_content = content
            representation = "storage"
        else:
            # Legacy wiki markup
            storage_content = content
            representation = "wiki"

        result: dict[str, Any] = self._client.create_page(
            space=space,
            title=title,
            body=storage_content,
            parent_id=parent_id,
            representation=representation,
            editor="v2",  # Use new Confluence editor (Fabric editor)
        )

        logger.info(f"Created page: {title} (ID: {result['id']})")
        return result

    def update_page(
        self,
        page_id: str,
        title: str,
        content: str,
        version_comment: str | None = None,
        content_format: str = "markdown",
    ) -> dict[str, Any]:
        """
        Update an existing Confluence page.

        Args:
            page_id: Page ID to update
            title: New page title
            content: New page content (markdown by default)
            version_comment: Comment for version history
            content_format: Content format - 'markdown' (default), 'storage', or 'wiki'

        Returns:
            Updated page data
        """
        # Get current version
        current_page = self.get_page(page_id)
        if not current_page:
            raise ValueError(f"Page not found: {page_id}")

        current_version = current_page["version"]["number"]

        # Convert content based on format
        if content_format == "markdown":
            # Convert markdown to Confluence storage format (XHTML)
            storage_content = markdown_to_confluence_storage(content)
            representation = "storage"
        elif content_format == "storage":
            storage_content = content
            representation = "storage"
        else:
            # Legacy wiki markup
            storage_content = content
            representation = "wiki"

        result: dict[str, Any] = self._client.update_page(
            page_id=page_id,
            title=title,
            body=storage_content,
            representation=representation,
            minor_edit=False,
            version_comment=version_comment,
        )

        logger.info(
            f"Updated page: {title} (ID: {page_id}, "
            f"version: {current_version} -> {result['version']['number']})"
        )
        return result

    def find_or_create_page(
        self,
        title: str,
        content: str,
        space_key: str | None = None,
        parent_id: str | None = None,
        version_comment: str | None = None,
        skip_unchanged: bool = True,
    ) -> tuple[dict[str, Any], bool]:
        """
        Find an existing page by title or create a new one.

        If the page exists and content has changed, updates it with a new version.

        Args:
            title: Page title
            content: Page content
            space_key: Space key
            parent_id: Parent page ID for new pages
            version_comment: Comment for version history
            skip_unchanged: Skip update if content hash matches

        Returns:
            Tuple of (page data, was_created)
        """
        space = space_key or self.space_key

        # Check if page exists
        existing_page = self.get_page_by_title(title, space)

        if existing_page is None:
            # Create new page
            page = self.create_page(
                title=title,
                content=content,
                space_key=space,
                parent_id=parent_id,
            )
            return page, True

        # Page exists - check if content changed
        if skip_unchanged:
            existing_content = existing_page.get("body", {}).get("storage", {}).get("value", "")
            existing_hash = self.compute_content_hash(existing_content)
            new_hash = self.compute_content_hash(content)

            if existing_hash == new_hash:
                logger.info(f"Page unchanged, skipping update: {title}")
                return existing_page, False

        # Update existing page
        page = self.update_page(
            page_id=existing_page["id"],
            title=title,
            content=content,
            version_comment=version_comment,
        )
        return page, False

    def search_pages(
        self,
        query: str,
        space_key: str | None = None,
        limit: int = 10,
    ) -> list[dict[str, Any]]:
        """
        Search for pages in Confluence.

        Args:
            query: Search query
            space_key: Space key to search in
            limit: Maximum results

        Returns:
            List of matching pages
        """
        space = space_key or self.space_key

        cql = f'space = "{space}" AND text ~ "{query}"'
        results: dict[str, Any] = self._client.cql(cql, limit=limit)

        return list(results.get("results", []))


class CreatePageTool(BaseTool):
    """Tool to create a new Confluence page."""

    @property
    def name(self) -> str:
        return "create_page"

    @property
    def description(self) -> str:
        return "Create a new Confluence page"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Page title following naming convention",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "Page content in wiki markup or markdown format",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key (uses default if not provided)",
                "type": "string",
                "required": False,
            },
            "parent_id": {
                "description": "Parent page ID for hierarchy",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.create_page(
                title=kwargs["title"],
                content=kwargs["content"],
                space_key=kwargs.get("space_key"),
                parent_id=kwargs.get("parent_id"),
            )
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "url": f"{client.url}/wiki/spaces/{client.space_key}/pages/{page['id']}",
                },
                action="created",
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to create page: {str(e)}")


class UpdatePageTool(BaseTool):
    """Tool to update an existing Confluence page."""

    @property
    def name(self) -> str:
        return "update_page"

    @property
    def description(self) -> str:
        return "Update an existing Confluence page, creating a new version"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "page_id": {
                "description": "Confluence page ID",
                "type": "string",
                "required": True,
            },
            "title": {
                "description": "Page title",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "New page content",
                "type": "string",
                "required": True,
            },
            "version_comment": {
                "description": "Comment for version history",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()

            version_comment = kwargs.get("version_comment")
            if not version_comment:
                version_comment = client.generate_version_comment()

            page = client.update_page(
                page_id=kwargs["page_id"],
                title=kwargs["title"],
                content=kwargs["content"],
                version_comment=version_comment,
            )
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                },
                action="updated",
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to update page: {str(e)}")


class FindOrCreatePageTool(BaseTool):
    """Tool to find or create a Confluence page with version management."""

    @property
    def name(self) -> str:
        return "find_or_create_page"

    @property
    def description(self) -> str:
        return (
            "Find existing page by title or create new one. "
            "If exists, updates with new version (skips if unchanged)."
        )

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Page title following naming convention",
                "type": "string",
                "required": True,
            },
            "content": {
                "description": "Page content in wiki markup or markdown format",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
            "parent_id": {
                "description": "Parent page ID for new pages",
                "type": "string",
                "required": False,
            },
            "version_comment": {
                "description": "Comment for version history",
                "type": "string",
                "required": False,
            },
            "agent_name": {
                "description": "Name of the agent generating the content",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()

            version_comment = kwargs.get("version_comment")
            if not version_comment:
                version_comment = client.generate_version_comment(
                    agent_name=kwargs.get("agent_name"),
                )

            page, was_created = client.find_or_create_page(
                title=kwargs["title"],
                content=kwargs["content"],
                space_key=kwargs.get("space_key"),
                parent_id=kwargs.get("parent_id"),
                version_comment=version_comment,
            )

            action = "created" if was_created else "updated"
            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "url": f"{client.url}/wiki/spaces/{client.space_key}/pages/{page['id']}",
                    "version": page.get("version", {}).get("number", 1),
                },
                action=action,
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to find or create page: {str(e)}")


class SearchPagesTool(BaseTool):
    """Tool to search for pages in Confluence."""

    @property
    def name(self) -> str:
        return "search_pages"

    @property
    def description(self) -> str:
        return "Search for existing pages in Confluence"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "query": {
                "description": "Search query",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
            "limit": {
                "description": "Maximum number of results (default: 10)",
                "type": "integer",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            results = client.search_pages(
                query=kwargs["query"],
                space_key=kwargs.get("space_key"),
                limit=kwargs.get("limit", 10),
            )

            pages = [
                {
                    "id": r.get("content", {}).get("id"),
                    "title": r.get("content", {}).get("title"),
                    "type": r.get("content", {}).get("type"),
                }
                for r in results
            ]

            return ToolResult.success(pages, count=len(pages))
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to search pages: {str(e)}")


class GetPageTool(BaseTool):
    """Tool to get a Confluence page by ID."""

    @property
    def name(self) -> str:
        return "get_page"

    @property
    def description(self) -> str:
        return "Get content of an existing Confluence page by ID"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "page_id": {
                "description": "Confluence page ID",
                "type": "string",
                "required": True,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.get_page(kwargs["page_id"])

            if page is None:
                return ToolResult.failure(f"Page not found: {kwargs['page_id']}")

            return ToolResult.success(
                {
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                    "content": page.get("body", {}).get("storage", {}).get("value", ""),
                }
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to get page: {str(e)}")


class GetPageByTitleTool(BaseTool):
    """Tool to get a Confluence page by title."""

    @property
    def name(self) -> str:
        return "get_page_by_title"

    @property
    def description(self) -> str:
        return "Get a Confluence page by its title in a specific space"

    @property
    def parameters(self) -> dict[str, dict[str, Any]]:
        return {
            "title": {
                "description": "Exact page title",
                "type": "string",
                "required": True,
            },
            "space_key": {
                "description": "Confluence space key",
                "type": "string",
                "required": False,
            },
        }

    def execute(self, **kwargs: Any) -> ToolResult:
        try:
            client = ConfluenceClient.get_instance()
            page = client.get_page_by_title(
                title=kwargs["title"],
                space_key=kwargs.get("space_key"),
            )

            if page is None:
                logger.warning(
                    f"Page not found: {kwargs['title']} - it will be created if using find_or_create_page"
                )
                return ToolResult.success(
                    {
                        "status": "not_found",
                        "title": kwargs["title"],
                        "message": f"Page '{kwargs['title']}' does not exist yet",
                    }
                )

            return ToolResult.success(
                {
                    "status": "found",
                    "id": page["id"],
                    "title": page["title"],
                    "version": page["version"]["number"],
                    "content": page.get("body", {}).get("storage", {}).get("value", ""),
                }
            )
        except ApiError as e:
            return ToolResult.failure(f"Confluence API error: {str(e)}")
        except Exception as e:
            return ToolResult.failure(f"Failed to get page by title: {str(e)}")
