"""
Repository page creation node.

Creates the Level 2 parent page for a repository under the root parent page.
All topic documentation pages will be created as children of this repo page.

Page Hierarchy:
- Level 1: CONFLUENCE_PARENT_PAGE_ID (root parent from config)
- Level 2: Repo page (created by this node, named by repo name)
- Level 3: Topic pages (created by individual agents under repo page)
"""

from collections.abc import Callable
from typing import Any

from code2doc.agents.state import AgentState
from code2doc.tools.confluence_tools import ConfluenceClient
from code2doc.utils.logging import get_logger

logger = get_logger("agents.nodes.repo_page")


def create_repo_page_node() -> Callable[[AgentState], dict[str, Any]]:
    """
    Create the repository page creation node.

    This node creates a parent page for the repository under the configured
    CONFLUENCE_PARENT_PAGE_ID. All topic documentation pages will be created
    as children of this repo page.

    Returns:
        Repo page node function
    """

    def repo_page_node(state: AgentState) -> dict:
        """
        Create or find the repository parent page in Confluence.

        Args:
            state: Current graph state

        Returns:
            State updates with repo_page_id set
        """
        request = state["request"]
        confluence_space = request["confluence_space"]
        root_parent_page_id = request.get("parent_page_id")
        repo_name = state.get("repo_name")

        if not repo_name:
            logger.error("Repo page node: repo_name not set in state")
            return {
                "errors": state.get("errors", [])
                + ["Failed to create repo page: repo_name not set"],
            }

        # Create page title for the repository
        page_title = repo_name

        logger.info(
            f"Repo page node: Creating/finding repo page '{page_title}' "
            f"under parent {root_parent_page_id}"
        )

        try:
            client = ConfluenceClient.get_instance()

            # Create a simple placeholder content for the repo page
            # This page serves as a container for all topic documentation
            content = f"""# {repo_name}

This page contains documentation for the **{repo_name}** repository.

## Documentation Topics

The following documentation is available for this repository:

- Overview
- ERD (Entity Relationship Diagram)
- API Endpoints
- Event Schemas
- Design Documentation
- Local Run Guide
- Resource Dependencies

---

*This page is auto-generated by Code-2-Doc.*
"""

            # Find or create the repo page
            page, was_created = client.find_or_create_page(
                title=page_title,
                content=content,
                space_key=confluence_space,
                parent_id=root_parent_page_id,
                version_comment="Auto-generated repository documentation page",
            )

            repo_page_id = page["id"]
            action = "created" if was_created else "found existing"

            logger.info(f"Repo page node: {action} repo page '{page_title}' (ID: {repo_page_id})")

            return {
                "repo_page_id": repo_page_id,
                "generated_docs": {
                    **state.get("generated_docs", {}),
                    "_repo_page": repo_page_id,
                },
            }

        except Exception as e:
            logger.error(f"Repo page node failed: {e}")
            return {
                "errors": state.get("errors", []) + [f"Failed to create repo page: {str(e)}"],
            }

    return repo_page_node
